#
#	This file is part of the OrangeFox Recovery Project
# 	Copyright (C) 2021-2026 The OrangeFox Recovery Project
#
# OrangeFox-specific settings for OnePlus 9RT (martini)
#

# General
OF_USE_GREEN_LED := 0
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_NO_MIUI_PATCH_WARNING := 1

# A/B device (virtual AB)
export FOX_VIRTUAL_AB_DEVICE := 1

# Features
OF_ENABLE_LPTOOLS := 1
OF_QUICK_BACKUP_LIST := /boot;/data;
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_ADVANCED_SECURITY := 1
OF_ENABLE_APP_MANAGER := 1
OF_USE_NANO_EDITOR := 1
OF_FLASHLIGHT_ENABLE := 0

# Disable unwanted addons
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_DISABLE_DM_VERITY_FORCED_ENCRYPTION := 1

# Theme settings
OF_SCREEN_H := 2400
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 60
OF_STATUS_INDENT_RIGHT := 60
OF_CLOCK_POS := 1
OF_ALLOW_DISABLE_NAVBAR := 0

# Magisk
OF_MAGISK_ZIP := Magisk.zip
